fix stoploss and take profit orders
rabbitx-io/rabbitx-python-client pull request #15
Opened 2024-08-12 02:25 UTC by spoonsrusty

This PR fixes the OrderType, OrderGroup.create and OrderType.amend to work with stoploss and take profit limit orders.

In order for them to work they require:

- the order type changed from "stop_loss" to "stop_loss_limit"  ("stop_loss" and "take_profit" do not seem to work currently)
- a "trigger_price" and "size_percent" included in the order dict when creating or amending

I have tested this on my own setup and its working as expected.

2024-08-14 08:03 UTC, rabbitx-io commented on rabbitx/client/endpoints/order.py
> +    STOP_LOSS = 'stop_loss_limit'
please change the naming to STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT, add additional STOP_LOSS = 'stop_loss" and TAKE_PROFIT = 'take_profit' for market order stop loss / take profit

2024-08-14 08:04 UTC, rabbitx-io requested changes
please change the naming to STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT, add additional STOP_LOSS = 'stop_loss" and TAKE_PROFIT = 'take_profit' for market order stop loss / take profit

2024-08-18 04:29 UTC, spoonsrusty commented
> please change the naming to STOP_LOSS_LIMIT and TAKE_PROFIT_LIMIT, add additional STOP_LOSS = 'stop_loss" and TAKE_PROFIT = 'take_profit' for market order stop loss / take profit

Done.

On a side note I haven't managed to get a stop loss market order to be accepted via api. Is there documentation on this anywhere? Perhaps it has changed to 'stop_loss_market'  or similar?

As a workaround I use 'stop_loss_limit' and 'size_percent' with a 'price' set well below (or above) market price

2024-09-21 01:23 UTC, rabbitx-io approved these changes

2024-09-21 01:23 UTC, merged